#!/bin/bash

# OrangeFox 14.1 build configuration for kof.
export FOX_BUILD_DEVICE="kof"
export FOX_AB_DEVICE=1
export FOX_VIRTUAL_AB_DEVICE=1
export FOX_VANILLA_BUILD=1
export FOX_USE_LZ4_BINARY=1
export FOX_USE_ZSTD_BINARY=1
export FOX_USE_XZ_UTILS=1
export FOX_USE_TAR_BINARY=1
export FOX_USE_SED_BINARY=1
export FOX_USE_GREP_BINARY=1
export FOX_USE_BUSYBOX_BINARY=1
export FOX_USE_FSCK_EROFS_BINARY=1
export FOX_USE_UPDATED_MAGISKBOOT=1
export FOX_ENABLE_APP_MANAGER=1
export OF_ENABLE_LPTOOLS=1
export OF_ENABLE_ALL_PARTITION_TOOLS=1
export OF_WIPE_METADATA_AFTER_DATAFORMAT=1
export OF_BIND_MOUNT_SDCARD_ON_FORMAT=1
